NorskHelsenett/ror-web

package-lock.json
package.json

This pull request updates the `react-router` and `vite` dependencies to their latest versions. 
- Upgraded `react-router` to the latest version to ensure compatibility with the latest features and improvements.
- Updated `vite` to the latest version for enhanced performance and new capabilities.
These updates aim to improve the overall functionality and maintainability of the project. Please review the changes and let me know if there are any concerns.

✨ chore: update react-router and vite dependencies to latest

---

README.md
app/env.ts
package.json

switch to relying on nodes environmental variables rather than statically switching them in the build process (as it was with vite setup)

✨ fix: update environment variable handling

---

Dockerfile
app/env.ts

Removing prefix VITE_ for env vars

---

apps/web/__mocks__/data/clusters.ts
apps/web/app/clusters/[id]/page.tsx
apps/web/app/clusters/cluster-table.tsx
apps/web/app/clusters/page.tsx
apps/web/components/common/health-status.tsx
packages/design/src/components/icon-indicator.scss
packages/react/src/components/icon-indicator.tsx

This pull request includes several changes to improve the handling and display of cluster health status. 
The most important changes include:
- Addition of `HealthStatus` component
- Updates to mock data
- Use `CodeSnippet` component for displaying debug data.

feat(web): display health status on cluster page

---

README.md
package-lock.json
package.json
turbo/generators/config.ts
turbo/generators/package.json
turbo/generators/templates/component.scss.hbs
turbo/generators/templates/component.stories.tsx.hbs
turbo/generators/templates/component.tsx.hbs

This pull request adds a new feature to streamline the creation of new components using [Turbo Gen](https://turbo.build/repo/docs/guides/generating-code).
These changes will help improve the developer experience by automating the boilerplate setup for new components, saving time and reducing manual effort.

Add turbo gen for bootstraping react components

---

apps/web/app/clusters/metrics-board.tsx

chore(metrics-board): remove test tags

---

apps/docs/.storybook/preview-head.html
apps/docs/stories/Pagination.stories.tsx
apps/docs/stories/Table.stories.tsx
apps/web/__mocks__/handlers.ts
apps/web/__mocks__/utils/paginated-response.ts
apps/web/app/clusters/cluster-table.tsx
apps/web/app/clusters/page.tsx
apps/web/app/clusters/view-switch.tsx
apps/web/components/common/data-table/data-table.tsx
apps/web/components/common/data-table/index.tsx
apps/web/components/common/data-table/pagination.ts
packages/js-api-client/lib/resources/clusters/clusters.resource.ts
packages/react/src/components/pagination.tsx
packages/react/src/components/table/table.tsx
packages/react/src/main.tsx
packages/styles/scss/components/_index.scss
packages/styles/scss/components/button.scss
packages/styles/scss/components/pagination.scss
packages/styles/scss/components/table.scss
packages/styles/scss/css-variables/variables.scss

This pull request introduces a new pagination feature across the application. The key changes include:
1. Added a new `Pagination` component in the React codebase to handle pagination functionality.
2. Integrated the `Pagination` component into the `DataTable` component in the web application, enabling pagination support for data tables.
3. Implemented pagination for the clusters list view in the web application, allowing users to navigate through large sets of cluster data.
These changes will improve the user experience by providing a consistent and intuitive way to navigate through large datasets across the application.

Add pagination

---

apps/web/.eslintrc.json
apps/web/eslint.config.js
apps/web/package.json
package-lock.json

This pull request introduces a new ESLint plugin for the React Compiler. The plugin aims to improve the development experience by providing additional linting rules and checks specific to the React Compiler.

feat(web): add react-compiler eslint plugin

---

apps/docs/stories/Search.stories.tsx
packages/react/src/components/search.tsx
packages/react/src/components/table/index.tsx
packages/react/src/components/table/table-toolbar-search.tsx
packages/react/src/components/table/table.tsx
packages/react/src/hooks/use-combined-refs.ts
packages/react/src/main.tsx
packages/styles/scss/components/_index.scss
packages/styles/scss/components/search.scss
packages/styles/scss/components/table.scss
packages/styles/scss/css-variables/variables.scss
packages/styles/scss/reset.scss
packages/styles/scss/utilities/component-reset.scss
packages/styles/scss/utilities/visually-hidden.scss

This pull request adds a new search component to the application and refactors the existing table component to use the new search functionality.
The key changes include:
- Added a new `SearchComponent` that provides a search input and functionality to filter data
- Updated the `TableComponent` to leverage the new `SearchComponent` to allow users to search and filter the table data

Add search component

---

apps/web/src/app/(protected)/clusters/[id]/ingresses/page.tsx
apps/web/src/app/(protected)/clusters/[id]/layout.tsx
apps/web/src/app/(protected)/clusters/[id]/page.tsx
apps/web/src/app/(protected)/clusters/[id]/raw-data/page.tsx
apps/web/src/app/(protected)/clusters/page.tsx
packages/js-api-client/README.md
packages/js-api-client/src/core/create-api-client.ts

This pull request
- adds a README file to the `js-api-client` module.
- Renames some service properties for consistency

docs(js-api-client): add README

---

apps/docs/package.json
apps/docs/stories/StructuredList.stories.tsx
apps/docs/stories/Table.stories.tsx
package-lock.json
packages/react/src/components/structured-list.tsx
packages/react/src/main.tsx
packages/styles/scss/components/_index.scss
packages/styles/scss/components/structured-list.scss

This will add a component that can be used for simpler display of tabular data as an alternative to the the `Table` component.

Add a structured list component for simpler tabular data

---

apps/docs/stories/SeverityIcon.stories.tsx
packages/react/src/components/severity-icon.tsx
packages/react/src/main.tsx
packages/styles/scss/components/_index.scss
packages/styles/scss/components/severity-icon.scss
packages/styles/scss/css-variables/variables.scss

This PR will add a component to display a vulnerability’s severity using the CVSS score.

Add component for displaying vulnerability severity

---

apps/web/package.json
apps/web/src/components/shadcn/accordion.tsx
apps/web/src/components/shadcn/alert.tsx
apps/web/src/components/shadcn/input.tsx
package-lock.json

This PR adds three components from shadcn, [accordion](https://ui.shadcn.com/docs/components/accordion), [alert](https://ui.shadcn.com/docs/components/alert) and [input](https://ui.shadcn.com/docs/components/input).

Add accordion, alert and input

---

apps/web/src/services/ror-api.ts

This PR adds some documentation to ror-api, as I found the file slightly confusing myself.

Add documentation to ror-api

---

apps/web/package.json
apps/web/src/app/(protected)/clusters/page.tsx
apps/web/src/components/shadcn/multiselect.tsx
apps/web/src/components/shadcn/toggle-group.tsx
apps/web/src/components/ui/sort-select.tsx
package-lock.json

This PR adds the UI for the sorting feature, using shadcn components.

Add ui for sorting

---

apps/web/src/app/(protected)/clusters/[id]/layout.tsx
apps/web/src/app/(protected)/clusters/page-view.tsx
apps/web/src/components/ui/cluster-search.tsx
apps/web/src/components/ui/cluster/cluster-card.tsx

PR implements a responsive layout and make sure UI works for different screens and light/darkmode.

Complete cluster bar UI

---

apps/web/src/app/(protected)/clusters/page-view.tsx
apps/web/src/components/ui/cluster-search.tsx
apps/web/src/components/ui/sort-select.tsx

This pull request adds support for dynamic search result updates, improving the search logic, and refining the sorting behavior.

Implement clustercard search logic

---

apps/web/src/app/(protected)/clusters/page-view.tsx
apps/web/src/components/ui/cluster/cluster-card.tsx

This pull request updates the `ClusterCard` component in `apps/web/src/components/ui/cluster/cluster-card.tsx` to improve responsiveness and layout behavior using container queries. The changes primarily focus on adding responsive styles for better handling of smaller screen sizes.

Fix card overflow on small screens

---

apps/web/src/middleware.ts

This PR adds redirect to sign-in when access token has run out

Fix access token bug

---

apps/web/package.json
apps/web/src/app/(protected)/clusters/[id]/cluster-metrics.tsx
apps/web/src/app/(protected)/clusters/[id]/layout.tsx
apps/web/src/app/(protected)/clusters/[id]/page.tsx
apps/web/src/components/shadcn/button.tsx
apps/web/src/components/shadcn/resizable.tsx
apps/web/src/components/shadcn/scroll-area.tsx
apps/web/src/components/ui/cluster/cluster-details.tsx
package-lock.json
package.json

This pull request introduces the replacement of cluster page components with a more modular `ClusterDetails` component.
* Introduced a new `Resizable` component (`resizable.tsx`) for resizable panels, leveraging `react-resizable-panels`.
* Added a `ScrollArea` component (`scroll-area.tsx`) using `@radix-ui/react-scroll-area` for scrollable areas with custom styling.
* Updated button styles in the `button.tsx` file to adjust the default variant for better visual consistency.
* Replaced multiple individual cluster-related components (`ClusterMetrics`, `ClusterMetadataCard`, etc.) with a single `ClusterDetails` component for a unified layout. The new component uses a grid layout with resizable and draggable panels. This utilizes the [react-grid-layout …

Implement dynamic dashboard

---

apps/web/src/app/(protected)/clusters/[id]/node-pools/edit-node-pool/page.tsx
apps/web/src/app/(protected)/clusters/[id]/node-pools/new-node-pool/page.tsx
apps/web/src/app/(protected)/clusters/[id]/node-pools/page-view.tsx
apps/web/src/config/routes.ts

This pull request introduces changes to support editing node pools in the application. This includes adding a new page for editing node pools, updating the routes configuration, and replacing the edit button's functionality with a link to the new edit page.

Add edit cluster page

---

apps/web/src/app/(protected)/clusters/cluster-table.tsx
apps/web/src/components/ui/cluster/cluster-card.tsx
apps/web/src/components/ui/cluster/cluster-details.tsx
apps/web/src/components/ui/cluster/cluster-header.tsx
apps/web/src/components/ui/cluster/health-circle.tsx
packages/js-api-client/src/schemas/kubernetes-cluster.ts

This pull request aims to facilitate a changing KubernetesCluster resource, making the site expect a less strict object.

Update KubernetesCluster schema

---

apps/web/src/components/ui/cluster/cluster-details.tsx
apps/web/src/components/ui/copy-button.tsx

This pull request introduces responsive layouts for the `ClusterDetails` component by integrating the `react-grid-layout` library's responsive features and refines the behavior of the `CopyButton` component. The most significant updates include transitioning to a responsive grid layout, enabling breakpoint-specific layouts, and improving layout state management.

Ensure responsive cluster dashboard

---

apps/web/src/components/ui/cluster/cluster-header.tsx
apps/web/src/components/ui/cluster/health-circle.tsx

This pull request updates the `ClusterHeader` and `HealthCircle` components to improve responsiveness, accessibility, and visual consistency. Key changes include enhancing the layout for better adaptability across screen sizes and refactoring the `HealthCircle` component for cleaner and more maintainable code.

Add more responsiveness to header

---

apps/web/src/app/(protected)/layout.tsx
apps/web/src/app/layout.tsx
apps/web/src/components/ui/cluster/cluster-card.tsx
apps/web/src/utils/renderApiError.ts

This pull request introduces error handling improvements for layout components, a minor UI adjustment, and a bug fix in the `RenderApiError` utility. The most significant changes include adding error boundaries to layout components, updating a UI element's styling, and fixing button links in the error rendering utility.

Fix error page

---

apps/web/__mocks__/data/clusters.ts
apps/web/src/app/(protected)/clusters/cluster-table.tsx
apps/web/src/app/(protected)/clusters/page.tsx
apps/web/src/components/ui/cluster/cluster-card.tsx
apps/web/src/components/ui/cluster/cluster-header.tsx
apps/web/src/utils/env-colors.ts

This pull request updates environment values and their associated color mappings for clusters, introduces new environments, and refactors how environment colors are managed across the codebase.

Add kurs, mgmt and undefined envs

---

apps/web/package.json
apps/web/src/app/(protected)/statistics/page-view.tsx
apps/web/src/app/(protected)/statistics/page.tsx
apps/web/src/components/app-sidebar-content.tsx
apps/web/src/components/shadcn/chart.tsx
apps/web/src/config/routes.ts
apps/web/src/features/statistics/utils/versions.ts
package-lock.json

This pull request introduces a new statistics feature to the web application, including a statistics page displaying version usage charts, utilities for aggregating version data, and sidebar navigation updates. It also adds a reusable chart component system using Recharts and ensures proper routing for the new statistics section.

Add statistics page
